#!/usr/bin/env python


def write_cube(filename, griddata, atomdata):
    with open(filename, "w") as f:
        #header, comments
        f.write("Cube file generated by icecube\n")
        f.write("Title card\n")
        #header 
        f.write("{} {} {} {} {}\n".format(atomdata.natoms, gridata.origin[0], griddata.origin[1], griddata.origin[2]))
        #header, box info. N is number of points, ij is increments. Data for X/Y/Z axis
        f.write("{} {} {} {}\n".format(griddata.Nx, griddata.xx, griddata.xy, griddata.xz))
        f.write("{} {} {} {}\n".format(griddata.Ny, griddata.yy, griddata.yy, griddata.yz))
        f.write("{} {} {} {}\n".format(griddata.Nz, griddata.zy, griddata.zy, griddata.zz))
        #header atoms
        for i in range(atomdata.natoms):
            f.write("{} {} {} {} {}\n".format(atomdata.icharge[i], atomdata.fcharge[i], atomdata.x[i], atomdata.y[i], atomdata.z[i]))
        #main data
        counter = 0 
        for i in range(Nx):
            for j in range(Ny):
                for k in range(Nz):
                    f.write("{}".format(griddata.data[i,j,k]))
                    counter += 1
                    if counter % 6 == 0:
                        f.write("\n")
                f.write("\n")
